// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvjgpqmqybtlazabzszo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2amdwcW1xeWJ0bGF6YWJ6c3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4MjQyNTgsImV4cCI6MjA3ODQwMDI1OH0.vvqlkJy7OfaBUHgZBlQVLZrCkz6FTydza35Wn03fxSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});